import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL")
TEMPERATURE = float(os.getenv("TEMPERATURE"))
MAX_OUTPUT_TOKENS = int(os.getenv("MAX_OUTPUT_TOKENS"))
TOP_K = int(float(os.getenv("TOP_K")))
TOP_P = int(float(os.getenv("TOP_P")))
MAX_RETRIES = int(os.getenv("MAX_RETRIES"))
BASE_DELAY = int(os.getenv("BASE_DELAY"))
MAX_DOCS = int(os.getenv("MAX_DOCS"))
VECTOR_SEARCH_K = int(os.getenv("VECTOR_SEARCH_K"))
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
CHUNK_SIZE = int(os.getenv("CHUNK_SIZE"))
CHUNK_OVERLAP = int(os.getenv("CHUNK_OVERLAP"))
PDF_FILE = os.getenv("PDF_FILE") 

CURRENT_DIR = Path(__file__).parent.absolute()
DATA_DIR = CURRENT_DIR / os.getenv("DATA_DIR")
JSON_FILE = os.getenv("JSON_FILE")
SQL_FILE = os.getenv("SQL_FILE")
TFIDF_MATRIX_FILE = os.getenv("TFIDF_MATRIX_FILE")
VECTORIZER_FILE = os.getenv("VECTORIZER_FILE")
STOPWORDS_FILE = os.getenv("STOPWORDS_FILE")
MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_PORT = os.getenv("MYSQL_PORT")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")
LOCAL_URL = os.getenv("LOCAL_URL")
PRODUCTION_URL = os.getenv("PRODUCTION_URL")
CONVERT_FILE = os.getenv("CONVERT_FILE")